#!/bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

source ~/.config/bspwm/monitors.sh

bspc config border_width 1
bspc config borderless_monocle true
bspc config focus_follows_pointer true
bspc config focused_border_color "#ebdbb2"
bspc config gapless_monocle true
bspc config normal_border_color "#665c54"
bspc config single_monocle true
bspc config split_ratio 0.50
bspc config window_gap 0

xsetroot -cursor_name left_ptr &
xsetroot -solid "#282828" &
