#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

source ./monitors.sh

bspc config border_width 0
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle true
bspc config split_ratio 0.52
bspc config window_gap 0
