#!/bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

bspc config border_width 1
bspc config borderless_monocle true
bspc config focus_follows_pointer true
bspc config focused_border_color "#ebdbb2"
bspc config gapless_monocle true
bspc config normal_border_color "#7c6f64"
bspc config split_ratio 0.50
bspc config window_gap 0

source ~/.config/bspwm/monitors.sh

xsetroot -solid "#282828" &
