[general]
import = [
  "~/.config/alacritty/font_size.toml",
  "~/.config/alacritty/gruvbox_dark.toml"
]

[terminal.shell]
program = "zellij"

[window]
decorations = "None"

[font]
normal = { family = "JetBrains Mono" }

[mouse]
hide_when_typing = true
